name: Tidy document
on:
  workflow_dispatch: {}
  push:
    branches:
      - gh-pages

jobs:
  tidy:
    name: Tidy up
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install tidy
      - run: tidy -config .tidyrc -o index.html index.html
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "chore(tidy): tidy up document"
          commit-message: "Tidied up document using tidy-html5"
          branch: html-tidy
